### ISSUE TITLE
getVimVmByMor slow in bigger vCenters

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/vmware_web_service#112]
Hi,

We are currently upgrading from ManageIQ Ivanchuk to Kasparov. When we did the migration and connected the vCenters to Kasparov we noticed timeouts and long wait times. Most noticeable in:
- Provider full refresh (1h +) for bigger vCenters
- Long wait times when opening a VM Console (webmks). Wait times (200-400 sec)

We investigated the webconsole issue further and found the `vm.with_provider_object do |vim_obj|` line when getting the console is taking most of the time. This code generally is running from a priority worker.

Trying to isolate the issue even further we found the call `vim.getVimVmByMor(ems_ref)` was the underlying call the was taking a lot of time.

I have created a small script I can run to investigate the issue further. The script can be found here: https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-mor_test-rb

I used this script to gather some results from Ivanchuk and Kasparov against a big vCenter and a small vCenter. Comparing the ivanchuck to the kasparov version it does not seems to use the vimBroker.

Timings and Logfiles (click the timings)

| getVimVmByMor | small vc (80 VM) | big vc (6000 VM) |
|---|---|---|
| ivanchuck with provider worker | [0.01 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-ivanchuck_backend_small_vc-log) | [0.01 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-ivanchuck_backend_big_vc-log) |
| ivanchuck UI worker | [2.5 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-ivanchuck_frondend_small_vc-log) | [160 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-ivanchuck_frontend_big_vc-log) |
| kasparov generic/prio worker | [2.4 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-kasparov_worker_small_vc-log) | [146 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-kasparov_worker_big_vc-log) |
| kasparov vmware-infra-operations worker | 3 sec | [200 sec](https://gist.github.com/evertmulder/062742dec37988fcc40bf90fd9d66c83#file-kasparov_84-vmware-infra-operations-2_worker_big-log) |

Looking at the logs a lot of vCenter communication is performed for every  getVimVmByMor on Kasparov, just to get vm details... On Ivanchuk the vimbroker seems to be caching a lot of the calls...

**Comment by agrare** [comment]
Hey @evertmulder thanks for the detailed write up!  The issue here is that the caching has moved to the VMware OperationsWorker in the jansa release and it would appear that the remote console queue item isn't properly being run on that worker.  I'll dig into this and

**Comment by evertmulder** [comment]
I also ran the script on the operation worker pod. The out of process script does seems to be using a cache. Is the cache a in-process, in -memory cache?

**Comment by agrare** [comment]
Okay I was able to reproduce the lag when the `remote_console_acquire_ticket` queue item is processed by the PriorityWorker while it builds the VM cache.  The issue was not having the queue_name set which caused the OperationsWorker not to pick up this queue item.  The OperationsWorker will not start processing queue items until after it has primed its cache (same behavior as the old VimBroker) and thus does not have this same lag/timeout issue.

**Comment by evertmulder** [comment]
We implemented the MR as well and the issue with the log waiting times when opening the console is completely resolved now. Big thanks for the fix @agrare! 👏 
Still working through a couple of issues like the long full refresh time and the power state actions seem to be broken, but I will have to dig into those issues a bit more. I create issues for the or perhaps start a discussion on gitter for those...

**Comment by agrare** [comment]
Awesome thanks @evertmulder 

For the refresh issue you might try applying the patch at the bottom of [[this comment]](https://github.com/ManageIQ/manageiq-providers-vmware/issues/745#issuecomment-983928538) and see if that resolves it for you.  Yeah feel free to ping me on gitter and we can work on figuring out what is going on.
