### ISSUE TITLE
Test artifacts

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/vmware_web_service#13]
Not sure if it's coming from this gem specifically or not, but I see the following in ManageIQ's test output:

```
(VimHash) xsiType: <VirtualDisk>  vimType: <>
. (VimArray) xsiType: <ArrayOfHostInternetScsiHbaStaticTarget>  vimType: <>
```

Not sure where it's coming from, but it needs to be removed.

**Comment by agrare** [comment]
@Fryguy I think this is coming from here: https://github.com/ManageIQ/manageiq/blob/master/spec/models/miq_request_task/dumping_spec.rb#L29-L52

If I run just that test I see the same output:
```
rspec spec/models/miq_request_task/dumping_spec.rb
Randomized with seed 31592
 (VimHash) xsiType: <VirtualDisk>  vimType: <>
. (VimArray) xsiType: <ArrayOfHostInternetScsiHbaStaticTarget>  vimType: <>
.....
```

**Comment by Fryguy** [comment]
Interesting...I'll move this issue to ManageIQ then.

@miq-bot move_issue manageiq
